version: '3.5'

services:
  api1:
    container_name: api1
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 60s sh docker-entrypoint.sh
    restart: always
    build: 
      context: ./src
    ports:
      - "8000"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1GB'

  api2:
    container_name: api2
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 60s sh docker-entrypoint.sh
    restart: always
    build: 
      context: ./src
    ports:
      - "8000"
    depends_on:
      - postgres      
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1GB'

  nginx:
    image: nginx:latest
    container_name: api_nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.5GB'

  postgres:
    image: postgres:latest
    container_name: api_database
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./pgdata:/var/lib/postgresql      
    ports:
      - "5432"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'
