version: '3'

services:
  api1:
    container_name: api1
    entrypoint: sh docker-entrypoint.sh
    restart: always
    build: 
      context: ./src
    ports:
      - "8000"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.88GB'

  api2:
    container_name: api2
    entrypoint: sh docker-entrypoint.sh
    restart: always
    build: 
      context: ./src
    ports:
      - "8000"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.88GB'

  nginx:
    image: nginx:latest
    container_name: api_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  postgres:
    image: postgres:latest
    container_name: api_database
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.74GB'
